name: Publish to npm registry (manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: git config --global user.email "github-action@users.noreply.github.com"
      - run: git config --global user.name "GitHub Action"
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Publish production package to npm
        run: npm publish --access public --tag latest
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
